pandoc index.md -c files/style.css -c files/custom.css --template files/template.html -o build/index.html
pandoc datasets/bottle.md -c files/style.css -c files/custom.css --template files/template.html -o build/bottle.html
pandoc datasets/cable.md -c files/style.css -c files/custom.css --template files/template.html -o build/cable.html
pandoc datasets/capsule.md -c files/style.css -c files/custom.css --template files/template.html -o build/capsule.html
pandoc datasets/carpet.md -c files/style.css -c files/custom.css --template files/template.html -o build/carpet.html
pandoc datasets/grid.md -c files/style.css -c files/custom.css --template files/template.html -o build/grid.html
pandoc datasets/hazelnut.md -c files/style.css -c files/custom.css --template files/template.html -o build/hazelnut.html
pandoc datasets/leather.md -c files/style.css -c files/custom.css --template files/template.html -o build/leather.html
pandoc datasets/metal_nut.md -c files/style.css -c files/custom.css --template files/template.html -o build/metal_nut.html
pandoc datasets/pill.md -c files/style.css -c files/custom.css --template files/template.html -o build/pill.html
pandoc datasets/screw.md -c files/style.css -c files/custom.css --template files/template.html -o build/screw.html
pandoc datasets/tile.md -c files/style.css -c files/custom.css --template files/template.html -o build/tile.html
pandoc datasets/toothbrush.md -c files/style.css -c files/custom.css --template files/template.html -o build/toothbrush.html
pandoc datasets/transistor.md -c files/style.css -c files/custom.css --template files/template.html -o build/transistor.html
pandoc datasets/wood.md -c files/style.css -c files/custom.css --template files/template.html -o build/wood.html
pandoc datasets/zipper.md -c files/style.css -c files/custom.css --template files/template.html -o build/zipper.html
